language: python
python:
  - "3.7"
dist: xenial
sudo: required
install:
  - pip install -e .
  - pip install coverage codacy-coverage
script:
  - coverage run -m unittest discover -v
  - coverage xml
  - python-codacy-coverage -r coverage.xml